### ISSUE TITLE
Add PyYaml library

### ISSUE THREAD

**Issue by raitraidma** [ppodgorsek/docker-robot-framework#103]
`pip install pyyaml==3.13`

Then it is possible to use configuration files in YAML format.

**Comment by ppodgorsek** [comment]
Could you provide an example file, along with a command-line example of how you launch your tests written in YAML format please?

**Comment by raitraidma** [comment]
Here is an example, where variables are stored in a YAML file: [robot-yaml-example.zip](https://github.com/ppodgorsek/docker-robot-framework/files/2299378/robot-yaml-example.zip)

**Comment by ppodgorsek** [comment]
I had a look at your example but I don't see the added advantage of YAML here. Why not simply define the variables in your Robot file?

    *** Variables ***
    ${BROWSER} chrome
    ${BAIDU_URL} https://www.baidu.com
    ${BING_URL} https://www.bing.com
    ${GOOGLE_URL} https://www.google.com
    ${YAHOO_URL} https://search.yahoo.com

Are there other cases where it could be used?

**Comment by raitraidma** [comment]
In this example it does not have any advantage. It is just an example how to use variables file. But I have used variable files to pass different values when running tests against different environments. Then I only have to change the reference to the variable file (e.g `robot --variablefile ./variables-test-azure.yaml .`)

Variables file for local tests:
```
BROWSER: chrome
HEADLESS: false
SITE_URL: https://localhost
```

Variables file for same tests but in another environment:
```
BROWSER: chrome
HEADLESS: true
SITE_URL: https://www.smt-to-test.com
```

**Comment by ppodgorsek** [comment]
Having environment-specific files is already possible with the OOTB Robot functionality, as the `--variablefile` command line option also works with `*.py` files containing standard Robot variables.

**Comment by ppodgorsek** [comment]
I am closing this issue, as there are no clear benefits to introducing the pyyaml library.

**Comment by Noordsestern** [comment]
Using [YAML for variable files is a builtin feature from robot framework](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#variable-file-as-yaml). However, in order to use this feature, you require pyyaml otherwise Robot Framework throws an error that PyYaml is missing.

Robot Framework Foundation even provided fixes for this feature during their latest release 3.1.2.

Please consider adding PyYaml in your image in order to support a base functionality in Robot Framework. You are right, we could achive the same thing by using *py files or simply write huge variable tables in robot-files. But YAML is easier to read for non-programmers. And being accessable for non-programmers is the core advantage of robot framework. When I automate processes for my colleagues, they feel more comfortable reading or even writing YAML files than python.

**Comment by ppodgorsek** [comment]
I checked the link provided and I can indeed see a big advantage in creating lists and maps in YAML instead of the standard format. I will therefore reopen the ticket to provide it.
