### ISSUE TITLE
Permission Denied when mounting a results folder

### ISSUE THREAD

**Issue by pilvikala** [ppodgorsek/docker-robot-framework#277]
**Describe the bug**
Following the instructions in the readme on how to start the container, the container fails to run any tests and prints out the following error:

```shell
[ ERROR ] Opening output file '/opt/robotframework/reports/output.xml' failed: Permission denied

Try --help for usage information.
```
**To Reproduce**
1. Create a folder with tests named tests.
2. Make sure there is no folder called results.
3. Run `docker run -v ${PWD}/results:/opt/robotframework/reports:Z -v ${PWD}/tests:/opt/robotframework/tests:Z ppodgorsek/robot-framework:latest`
4. The error above shows up in the console

**Expected behavior**
Tests from the ./tests are executed and the report is stored in the ./results folder

**Please provide any relevant information, such as:**
 - OS: Ubuntu 20.04
 - Docker version 19.03.8, build afacb8b7f0

**Comment by ppodgorsek** [comment]
Thank you @pilvikala for the bug report. This might be due to the recent change of default user in the container.

The image used to run using the root user (no issues with permissions) but, for security reasons, it has been recently changed to rely on a user with PID 1000 and GID 1000.
The folders which you mount when running the container must be accessible by that user.

Another option is to set the user by adding `--user=` on the command line, it accepts any PID.

More information can be found in the README file if needed.

**Comment by pilvikala** [comment]
I found that, thanks. It would be nice to update the documentation so the information is closed to how one should run the docker container.

**Comment by ppodgorsek** [comment]
@pilvikala there is already such information in the README. All Docker images run with a default user, this is standard practice, so I don't want to update all examples with an unnecessary `--user` parameter.

Could you let me know what you feel is missing in order to complete it please?

**Comment by pilvikala** [comment]
Alright then, my mistake. Let's just close this :) Thanks for help!
