### ISSUE TITLE
Adding robotframework-SikuliLibrary

### ISSUE THREAD

**Issue by simonfreeman80** [ppodgorsek/docker-robot-framework#329]
Will be possible to add Sikuli Library support?
This will really increase opportunity to include image recog/ocr in the testing script inside the container.
Thank you

**Comment by UltimateDogg** [comment]
Reading the documentation, it seems like you would need an external component to actually run these tests (since it uses the remote library) and also the server is written in java. This would probably need a lot of components to be added to this image. Your best best would probably be to extend this image with your own items to install this library since adding the jdk alone would increase the size quite a bit.

**Comment by simonfreeman80** [comment]
I was thinking about this as an alternative (no java required): [https://www.eficode.com/blog/introducing-imagehorizonlibrary]

**Comment by ppodgorsek** [comment]
The feature allowing to dynamically install additional dependencies has finally been implemented as part of #376 and the details can be found in the README: https://github.com/ppodgorsek/docker-robot-framework#installing-additional-dependencies

You could therefore install the Sikuli alternative for Python:
https://pypi.org/project/sikulpy/
