### ISSUE TITLE
Currently published 4.0.0 tag does not contain apk

### ISSUE THREAD

**Issue by appliednate** [ppodgorsek/docker-robot-framework#423]
**Describe the bug**
The currently hosted version of the 4.0.0 tag of the image does not contain apk.  Previous versions did and this 4.0.0 tag was uploaded at the same as the 5.0.0 image

**To Reproduce**
Download latest image and attempt to use apk.

**Expected behavior**

**Robot template**
Any Robot template which could help reproduce the issue.

**Screenshots**
![image](https://user-images.githubusercontent.com/98473532/197227997-dd15ef11-82c0-4b06-bcce-625a00c0d754.png)

**Please provide any relevant information, such as:**

**Additional context**

**Comment by mrdgo** [comment]
`apk` belongs to alpine linux. This image is based on fedora, use `dnf`

**Comment by ppodgorsek** [comment]
It seems like the `4.0.0` tag on Docker Hub was incorrectly pushed. The git tag relies on Alpine Linux but the pushed image relies on Fedora, likely due to a wrong container alias being pushed. Furthermore, Docker Hub doesn't seem to detect the OS of that `4.0.0` tag. I have therefore deleted the tag on Docker Hub to avoid confusion. (it is still available on git if anyone needs it for their own build)

As mentioned above by @mrdgo , this project has now migrated to Fedora / dnf, hence why no other Alpine image will be maintained or published.
