### ISSUE TITLE
Can not run selenium test with option BROWSER=edge

### ISSUE THREAD

**Issue by khanhcd92** [ppodgorsek/docker-robot-framework#450]
I tried with below command but it was not run
```
docker run -it --shm-size=2g \
            -v `pwd`/test/selenium.robot:/opt/robotframework/tests/selenium.robot:Z \
            -e BROWSER=edge \
            ppodgorsek/robot-framework:latest
```

An exception was thrown as below
`WebDriverException: Message: unknown error: msedge failed to start: crashed.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from msedge location /opt/microsoft/msedge/msedge is no longer running, so msedgedriver is assuming that msedge has crashed.)`

**Comment by ppodgorsek** [comment]
I cannot reproduce the issue, it is working fine on my computer and in the automated CI pipeline.

Which device are you using?

**Comment by khanhcd92** [comment]
@ppodgorsek 

I ran it on server as below:
NAME="Amazon Linux"
VERSION="2023"
ID="amzn"
ID_LIKE="fedora"
VERSION_ID="2023"
PLATFORM_ID="platform:al2023"
PRETTY_NAME="Amazon Linux 2023"
ANSI_COLOR="0;33"
CPE_NAME="cpe:2.3:o:amazon:amazon_linux:2023"
HOME_URL="https://aws.amazon.com/linux/"
BUG_REPORT_URL="https://github.com/amazonlinux/amazon-linux-2023"
SUPPORT_END="2028-03-01

**Comment by khanhcd92** [comment]
@ppodgorsek pp

Could you give more information about your computer and in the automated CI pipeline ?

**Comment by ppodgorsek** [comment]
A 5-minute online search revealed that Amazon servers (EC2 Graviton, ARM-based) cannot run linux/amd64 images... (the image's architecture is shown on the Docker Hub)

I added explanations in the troubleshooting section of the README. (see PR #451)

I also created a separate enhancement to build and push images for multiple architectures, rather than only linux/amd64. (see #455)
