### ISSUE TITLE
Chromedriver has the wrong version?

### ISSUE THREAD

**Issue by balbinas** [ppodgorsek/docker-robot-framework#62]
Hey Paul, thanks for this docker, I'm trying to install it in a Bitbucket Pipeline but it always fails when it tries to "Open Browser" in my tests. I have a feeling it's the chromedriver version you're using..? I'm looking all over the internet and it says chromedriver is on version '2.35' and you're using '63.0' just like chromium, could it be a typo?

**Comment by balbinas** [comment]
This is the error I get when the "Open Browser" command runs.

`WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.33,platform=Linux 4.14.11-coreos x86_64)`

**Comment by ppodgorsek** [comment]
Hello Balbina,

Regarding the version used, it is normal that the versions for Chromium and its driver are identical, this is the package versioning for Fedora which allows to know if the driver will be compatible with the installed version of Chromium. As you can see in your logs, the driver is in fact in version 2.33.

The logs sometimes don't show an explicit message and this "exited abnormally" message can be caused by many different things.

Could you try run the container again by mounting the following volume below too please?

    -v `pwd`/test/logs:/var/log:Z

After having run the tests, the folder should contain the `chromedriver` logs, which will be helpful to debug further.

**Comment by ppodgorsek** [comment]
As pointed out by @christian-roggia, issues can occur with Chromium running headless, as [this thread](https://github.com/elgalu/docker-selenium/issues/20) explains.

Could you retry by adding `--shm-size=1g` to the run command please?

**Comment by ppodgorsek** [comment]
This issue cannot be reproduced but is probably related to the shm issue with Chromium.
A troubleshooting section about it has [already been added to the README](https://github.com/ppodgorsek/docker-robot-framework/pull/72).
